version: '3'
services:
  historyserver:
    build:
      context: ./cloudera-cluster-historyserver
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-historyserver
    hostname: historyserver
  hdfs-namenode:
    build:
      context: ./cloudera-cluster-hdfs-namenode
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-hdfs-namenode
    hostname: hdfs-namenode
  hdfs-secondarynamenode:
    build:
      context: ./cloudera-cluster-hdfs-secondarynamenode
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-hdfs-secondarynamenode
    hostname: hdfs-secondarynamenode
  yarn-resourcemanager:
    build:
      context: ./cloudera-cluster-yarn-resourcemanager
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-yarn-resourcemanager
    hostname: yarn-resourcemanager
  datanode1:
    build:
      context: ./cloudera-cluster-datanode
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-datanode
    hostname: datanode1
  datanode2:
    build:
      context: ./cloudera-cluster-datanode
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-datanode
    hostname: datanode2
  zookeeper1:
    build:
      context: ./cloudera-cluster-zookeeper
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-zookeeper
    hostname: zookeeper1
    environment:
      ZOOKEEPER_MYID: "1"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_SERVERS: "server.1=zookeeper1:2201:8301\nserver.2=zookeeper2:2202:8302\nserver.3=zookeeper3:2203:8303"
  zookeeper2:
    build:
      context: ./cloudera-cluster-zookeeper
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-zookeeper
    hostname: zookeeper2
    environment:
      ZOOKEEPER_MYID: "2"
      ZOOKEEPER_CLIENT_PORT: "2182"
      ZOOKEEPER_SERVERS: "server.1=zookeeper1:2201:8301\nserver.2=zookeeper2:2202:8302\nserver.3=zookeeper3:2203:8303"
  zookeeper3:
    build:
      context: ./cloudera-cluster-zookeeper
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-zookeeper
    hostname: zookeeper3
    environment:
      ZOOKEEPER_MYID: "3"
      ZOOKEEPER_CLIENT_PORT: "2183"
      ZOOKEEPER_SERVERS: "server.1=zookeeper1:2201:8301\nserver.2=zookeeper2:2202:8302\nserver.3=zookeeper3:2203:8303"
  gateway:
    build:
      context: ./cloudera-cluster-gateway
      dockerfile: Dockerfile
    image: ipogudin/cloudera-cluster-gateway
    hostname: gateway
    container_name: gateway

networks:
 default:
  external:
    name: cloudera-cluster-net